I've recently found the link below, which has all match results and average odds in one place.  This is convenient!  However, this only has matches after roughly the year 1997, but it does have women's matches and doubles!  In this notebook, we'll try to write a scraper for this website...

In [1]:
from tennis_new.fetch.tennis_explorer.matches.scraper import TennisExplorerParser

In [19]:
from datetime import datetime

te = TennisExplorerParser(datetime(2015, 6, 13))

In [20]:
te.process()

In [21]:
te.write_df()

In [ ]:
URL = 'https://www.tennisexplorer.com/results/?year=2010&month=05&day=06'

In [1]:
import pandas as pd
from tennis_new.fetch.tennis_explorer.defs import JD_PATH

jd = pd.read_csv(JD_PATH)

/Users/siddhantjagadish/Documents/DataProjects/tennis_new/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [15]:
(jd['p1_sets_won'] == 1).value_counts()

False    909871
True      35796
Name: p1_sets_won, dtype: int64

In [34]:
jd[jd['tourney_name'].map(lambda x: 'FUTURE' not in x.upper() and 'CHALL' not in x.upper())]['tourney_name'].value_counts()

Bundesliga - men             7265
Davis Cup                    6765
French Open                  5273
US Open                      5273
Australian Open              5161
Wimbledon                    5159
Miami                        2869
Italian Team Championship    2851
Indian Wells                 2561
Rome                         1738
Monte Carlo                  1714
Cincinnati                   1714
Queen's Club                 1609
France - Championship        1599
Barcelona                    1566
Hamburg                      1458
Paris - Masters              1420
Washington                   1417
Madrid - Masters             1291
Tokyo (Japan Open)           1214
Kitzb√ºhel                    1151
Stuttgart                    1136
Stockholm                    1122
Moscow                       1113
Marseille                    1113
Doha                         1111
Munich                       1109
Halle                        1100
Umag                         1082
Sydney                       1081
                             ...
Paris - exhibition             20
Champions Tennis League        19
Barcelona - seniors            19
Hurlingham - exhibition        16
US Open pre-qualifier          15
St. Anton - exhibice           14
Sydney - seniors               14
Eindhoven - seniors            14
Luxembourg - seniors           14
Spain - Championship           14
Grand Cayman - seniors         14
Budapest - seniors             14
Stanford - seniors             14
Rio de Janeiro - seniors       14
Boston - seniors               13
Santiago - seniors             13
Edinburgh - seniors            10
Monterrey - seniors             8
Dubai - seniors                 8
Medellin - seniors              8
Newport - seniors               8
Mallorca - seniors              8
Hong Kong                       8
Charlotte - seniors             7
Hua Hin - exhibition            7
Asian Hopman Cup                7
Los Cabos - seniors             6
Brussels - seniors              5
Malaga Masters                  5
Hua Hin (exh.)                  1
Name: tourney_name, Length: 220, dtype: int64

In [27]:
jd['tourney_name'].value_counts()

Futures 2015                 46487
Futures 2014                 46432
Futures 2016                 45668
Futures 2017                 44736
Futures 2013                 43887
Futures 2018                 41356
Futures 2012                 41300
Futures 2011                 37793
Futures 08                   37775
Futures 07                   35896
Futures 09                   35598
Futures 2010                 34891
Futures 06                   33549
Futures 05                   30047
Futures 04                   26785
Futures 2019                 26062
Futures 03                   25134
Futures 02                   22285
Bundesliga - men              7265
Davis Cup                     6765
French Open                   5273
US Open                       5273
Australian Open               5161
Wimbledon                     5159
Miami                         2869
Italian Team Championship     2851
Indian Wells                  2561
Rome                          1738
Cincinnati                    1714
Monte Carlo                   1714
                             ...
Paris - exhibition              20
Champions Tennis League         19
Barcelona - seniors             19
Hurlingham - exhibition         16
US Open pre-qualifier           15
St. Anton - exhibice            14
Eindhoven - seniors             14
Rio de Janeiro - seniors        14
Budapest - seniors              14
Luxembourg - seniors            14
Spain - Championship            14
Stanford - seniors              14
Grand Cayman - seniors          14
Sydney - seniors                14
Santiago - seniors              13
Boston - seniors                13
Edinburgh - seniors             10
Medellin - seniors               8
Dubai - seniors                  8
Hong Kong                        8
Newport - seniors                8
Monterrey - seniors              8
Mallorca - seniors               8
Charlotte - seniors              7
Hua Hin - exhibition             7
Asian Hopman Cup                 7
Los Cabos - seniors              6
Brussels - seniors               5
Malaga Masters                   5
Hua Hin (exh.)                   1
Name: tourney_name, Length: 834, dtype: int64

In [19]:
jd[
    (jd['p1_sets_won'] == 3) &
    (jd['tourney_name'] == 'Vienna')
].sort_values('date')[[
    'date',
    'p1_name',
    'p2_name',
    
]]

              date        p1_name      p2_name
5515    1997-10-12  Ivanisevic G.  Rusedski G.
12468   1998-10-17     Sampras P.    Kucera K.
19506   1999-10-16    Rusedski G.    Kiefer N.
26661   2000-10-11      Koubek S.    Escude N.
26754   2000-10-14      Henman T.      Haas T.
34573   2001-10-13        Haas T.     Canas G.
65253   2002-10-13     Federer R.     Novak J.
103343  2003-10-12     Federer R.      Moya C.
143218  2004-10-17       Lopez F.     Canas G.
187277  2005-10-16    Ljubicic I.   Ferrero J.
235631  2006-10-15    Ljubicic I.  Gonzalez F.

In [23]:
score_cols = [x for x in jd if 'set' in x and 'sets_won' not in x]
score_cols

['p1_set1',
 'p1_set2',
 'p1_set3',
 'p1_set4',
 'p1_set5',
 'p2_set1',
 'p2_set2',
 'p2_set3',
 'p2_set4',
 'p2_set5']

In [24]:
jd[['p1_name', 'p2_name', 'date', 'tourney_name'] + score_cols][
    jd['p1_sets_won'] == 1
]

,p1_name,p2_name,date,tourney_name,p1_set1,p1_set2,p1_set3,p1_set4,p1_set5,p2_set1,p2_set2,p2_set3,p2_set4,p2_set5
4,Tillstrom M.,Black B.,1997-01-01,Adelaide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Johnson D.,Van Lottum J.,1997-01-06,Singapur challenger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,Black B.,Woodbridge T.,1997-01-08,Sydney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Reneberg R.,Burrieza-Lopez O.,1997-01-15,Australian Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,Stafford G.,Burillo J.,1997-01-15,Australian Open,6.0,6.0,3.0,NaN,NaN,0.0,1.0,0.0,NaN,NaN
174,Tramacchi P.,Van Herck J.,1997-01-15,Australian Open,6.0,6.0,6.0,3.0,NaN,7.0,3.0,4.0,2.0,NaN
228,Hrbaty D.,Berasategui A.,1997-01-18,Australian Open,6.0,7.0,6.0,2.0,NaN,3.0,6.0,7.0,0.0,NaN
241,Costa A.,Ferreira W.,1997-01-20,Australian Open,6.0,6.0,3.0,NaN,NaN,3.0,2.0,2.0,NaN,NaN
359,Ivanisevic G.,Radulescu A.,1997-01-31,Zagreb,6.0,1.0,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN
377,Grant G.,Golmard J.,1997-02-03,Wolfsburg challenger,5.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
480,Dreekmann H.,Champion T.,1997-02-12,Marseille,6.0,3.0,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN
534,Ivanisevic G.,Becker B.,1997-02-14,Dubai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
554,Enqvist T.,Rios M.,1997-02-16,Marseille,6.0,1.0,NaN,NaN,NaN,4.0,0.0,NaN,NaN,NaN
555,Sampras P.,Rusedski G.,1997-02-17,San Jose,3.0,5.0,NaN,NaN,NaN,6.0,0.0,NaN,NaN,NaN
573,Koubek S.,Goossens K.,1997-02-17,Punta del Este challenger,2.0,7.0,5.0,NaN,NaN,6.0,5.0,0.0,NaN,NaN
604,Norman D.,Ulihrach B.,1997-02-18,Antwerp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
710,Goellner M.,Damm M.,1997-02-21,Antwerp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
782,Woodbridge T.,Chesnokov A.,1997-02-25,Philadelphia,6.0,1.0,NaN,NaN,NaN,3.0,0.0,NaN,NaN,NaN
788,Hernandez A.,Rikl D.,1997-02-25,Salinas challenger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
789,Oncins J.,Etlis G.,1997-02-25,Salinas challenger,3.0,6.0,3.0,NaN,NaN,6.0,3.0,0.0,NaN,NaN
908,Bergh F.,Stafford G.,1997-03-05,Indian Wells challenger,7.0,2.0,NaN,NaN,NaN,6.0,0.0,NaN,NaN,NaN
927,Ivanisevic G.,Korda P.,1997-03-07,Rotterdam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936,Novak J.,Gross O.,1997-03-07,Indian Wells challenger,7.0,2.0,NaN,NaN,NaN,5.0,0.0,NaN,NaN,NaN
945,Voinea A.,Forget G.,1997-03-11,Indian Wells,4.0,4.0,NaN,NaN,NaN,6.0,2.0,NaN,NaN,NaN
989,Dosedel S.,Corretja A.,1997-03-12,Indian Wells,6.0,4.0,NaN,NaN,NaN,4.0,1.0,NaN,NaN,NaN
1042,Clement A.,Olhovskiy A.,1997-03-19,Saint Petersburg,7.0,4.0,NaN,NaN,NaN,5.0,1.0,NaN,NaN,NaN
1049,Voinea A.,Zabaleta M.,1997-03-20,Miami,5.0,7.0,6.0,NaN,NaN,7.0,5.0,6.0,NaN,NaN
1062,Clement A.,Rusedski G.,1997-03-20,Saint Petersburg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1090,Etlis G.,Reneberg R.,1997-03-22,Miami,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1165,Sampras P.,Dreekmann H.,1997-03-27,Miami,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945167,Duan J.,Matsui T.,2019-10-28,Shenzhen 2 challenger,7.0,4.0,NaN,NaN,NaN,5.0,1.0,NaN,NaN,NaN
945172,Shapovalov D.,Simon G.,2019-10-29,Paris - Masters,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
945219,Klein B.,Kelly D.,2019-10-29,Playford 2 challenger,4.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
945226,Ofner S.,Rodionov J.,2019-10-29,Eckental challenger,6.0,7.0,3.0,NaN,NaN,7.0,5.0,0.0,NaN,NaN
945255,Nagy P.,Cazaux A.,2019-10-29,Futures 2019,6.0,6.0,2.0,NaN,NaN,4.0,7.0,0.0,NaN,NaN
945265,Adamson A.,Haliak M.,2019-10-29,Futures 2019,6.0,3.0,NaN,NaN,NaN,2.0,0.0,NaN,NaN,NaN
945321,Al Mousa H.,Borsan D.,2019-10-29,Futures 2019,6.0,2.0,NaN,NaN,NaN,4.0,0.0,NaN,NaN,NaN
945335,Safiullin R.,Istomin D.,2019-10-30,Shenzhen 2 challenger,4.0,7.0,2.0,NaN,NaN,6.0,5.0,0.0,NaN,NaN
945340,Tseng C.,Matsui T.,2019-10-30,Shenzhen 2 challenger,7.0,2.0,NaN,NaN,NaN,6.0,1.0,NaN,NaN,NaN
945341,Li Z.,Jaziri M.,2019-10-30,Shenzhen 2 challenger,4.0,6.0,5.0,NaN,NaN,6.0,4.0,0.0,NaN,NaN
945352,King D.,Mmoh M.,2019-10-30,Charlottesville challenger,6.0,4.0,NaN,NaN,NaN,3.0,1.0,NaN,NaN,NaN
945354,Bangoura S.,Sock J.,2019-10-30,Charlottesville challenger,6.0,0.0,NaN,NaN,NaN,3.0,0.0,NaN,NaN,NaN
945360,Varillas Patino-Samudio J.,Luz O.,2019-10-30,Guayaquil challenger,7.0,2.0,NaN,NaN,NaN,6.0,0.0,NaN,NaN,NaN
945362,Coria F.,Lindell C.,2019-10-30,Guayaquil challenger,6.0,7.0,0.0,NaN,NaN,7.0,5.0,0.0,NaN,NaN
945388,Crawford O.,Descotte M.,2019-10-30,Futures 2019,6.0,4.0,NaN,NaN,NaN,3.0,0.0,NaN,NaN,NaN
945390,Carr S.,Butsch J.,2019-10-30,Futures 2019,6.0,2.0,NaN,NaN,NaN,2.0,0.0,NaN,NaN,NaN
945396,Moro Canas A.,Ross M.,2019-10-30,Futures 2019,3.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
945400,Furness E.,Fatic N.,2019-10-30,Futures 2019,4.0,6.0,NaN,NaN,NaN,6.0,3.0,NaN,NaN,NaN
945420,Cash J.,Van Den Berg B.,2019-10-30,Futures 2019,7.0,0.0,NaN,NaN,NaN,5.0,1.0,NaN,NaN,NaN
945432,Barreto Sanchez D.,Marti Pujolras A.,2019-10-30,Futures 2019,6.0,4.0,4.0,NaN,NaN,2.0,6.0,1.0,NaN,NaN
945439,Paulson A.,Safranek V.,2019-10-30,Futures 2019,7.0,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN
945461,Mora M.,Andreu Garcia F.,2019-10-30,Futures 2019,6.0,3.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
945472,Vivero Gonzalez P.,Pokotilov B.,2019-10-30,Futures 2019,6.0,4.0,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN
945494,Zhang Z.,Gojo B.,2019-10-31,Shenzhen 2 challenger,6.0,2.0,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN
945535,Andreev A.,Pena Lopez M.,2019-10-31,Futures 2019,5.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
945537,Carr S.,Witten J.,2019-10-31,Futures 2019,6.0,0.0,NaN,NaN,NaN,2.0,0.0,NaN,NaN,NaN
945567,Cacao T.,Alemany P.,2019-10-31,Futures 2019,7.0,4.0,NaN,NaN,NaN,6.0,1.0,NaN,NaN,NaN
945573,Friberg K.,Obert A.,2019-10-31,Futures 2019,6.0,2.0,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN
945582,Seifert S.,Crepatte B.,2019-10-31,Futures 2019,7.0,1.0,NaN,NaN,NaN,5.0,0.0,NaN,NaN,NaN
945625,Uchiyama Y.,Harris A.,2019-11-01,Playford 2 challenger,4.0,3.0,NaN,NaN,NaN,6.0,1.0,NaN,NaN,NaN

In [6]:
?pd.read_csv

In [ ]:
from tennis_new.fetch.tennis_explorer.helpers import *

In [ ]:
%pdb
from tennis_new.fetch.tennis_explorer.scraper import TennisExplorerTourneyParser

URL = 'charlottesville-challenger/2019/atp-men/' 

tp = TennisExplorerTourneyParser(URL)

In [ ]:
tp.details

In [ ]:
tp.to_df()

In [ ]:
tp.details.split(',')[:-2]

In [ ]:
tp.url.replace('/', '-')

In [ ]:
tp.details.strip('()').split(',')[2:]

In [ ]:
html.tostring(tree.xpath(".//h1")[0])

In [ ]:
html.tostring(tree.body.getchildren()[0].getchildren()[0])

In [ ]:
tree.xpath(".//div[@class='box boxBasic lGray']")[1].text

In [ ]:
from lxml import html
%pdb

from datetime import datetime
from tennis_new.fetch.tennis_explorer.scraper import TennisExplorerParser

te = TennisExplorerParser(datetime(2018, 3, 11))
te.process()
# te.write_df()

In [ ]:
sorted(te.to_df().columns)

In [ ]:
import pandas as pd
from tennis_new.fetch.tennis_explorer.defs import DATA_PATH
from pathlib import Path

In [ ]:
DATA_PATH

In [ ]:
import glob

all_match = pd.concat([pd.read_csv(x) for x in glob.glob('%s/match_results/*.csv' % DATA_PATH)])

In [ ]:
all_match[all_match['tourney_name'].map(lambda x: 'Future' not in x)].shape

In [ ]:
all_match.shape

In [ ]:
all_match.memory_usage().sum() / (1024. ** 2)

183 MB so far...

In [ ]:
all_match['match_link'].nunique()

In [ ]:
bettable = all_match[
    all_match['tourney_name'].map(lambda x: 'Future' not in x) &
    all_match['p1_odds'].notnull()
]
bettable.shape

In [ ]:
all_match['p1_odds'].notnull().sum()

In [ ]:
non_futures = all_match[all_match['tourney_name'].map(lambda x: 'Future' not in x)]

In [ ]:
non_futures['p1_odds'].notnull().sum()

In [ ]:
(bettable['p1_odds'] < bettable['p2_odds']).mean()

In just 3 months, I have 11k matches with odds, and 4.3k non-futures matches with odds...

In [ ]:
all_match['tourney_link'].isnull().value_counts()

There are 656k Futures matches with no tournament link -- have to get the surface match by match :(

In [ ]:
all_match['tourney_link'].nunique()

5300 unique tournaments...need to scrape surface from these...will take a little while.

In [ ]:
all_match[['p1_name', 'p1_link', 'p2_name', 'p2_link', 'date', 'tourney_name', 'p1_sets_won', 'p2_sets_won']]

In [ ]:
all_match.iloc[4]

In [ ]:
(res_df['p1_sets_won'] > res_df['p2_sets_won']).all()

In [ ]:
import re

def regex_strip_string(string):
    string = re.sub('\n', '', string).strip()
    string = re.sub('\r', '', string).strip()
    string = re.sub('\t', '', string).strip()
    return string

def _text(elem):
    t = elem.text
    if t:
        return regex_strip_string(t)
    else:
        return None

def _tail(elem):
    t = elem.tail
    if t:
        return regex_strip_string(t)
    else:
        return None


EXPECTED_HEADER_CLASSES = [
    't-name',
    'score',
    'score',
    'score',
    'score',
    'score',
    'score',
    'course',
    'course',
    'icons',
    'icons'
]

def get_tourney_name_type(span_children):
    assert len(span_children) == 2
    tourney_name = span_children[1].tail
    tourney_type = span_children[1].attrib['class']
    return tourney_name, tourney_type

def _parse_head_flags(tr):
    # TODO: Parse headers?
    children = tr.getchildren()
    assert all([child.tag == 'td' for child in children])
    classes = [child.attrib['class'] for child in children]
    assert classes == EXPECTED_HEADER_CLASSES
    tourney_name = children[0]
    maybe_link = tourney_name.getchildren()
    tourney_link = None
    if len(maybe_link) == 1:
        assert maybe_link[0].tag == 'a'
        tourney_link = maybe_link[0].attrib['href']
        tourney_name, tourney_type = get_tourney_name_type(maybe_link[0].getchildren())
    else:
        tourney_name, tourney_type = get_tourney_name_type(maybe_link)
    return {
        'tourney_name': tourney_name,
        'tourney_type': tourney_type,
        'tourney_link': tourney_link
    }

def _parse_time(time_elem):
    assert time_elem.attrib['class'] == "first time" 
    return _text(time_elem)

def _parse_player(player_elem):
    assert player_elem.attrib['class'] == 't-name'
    _ch = player_elem.getchildren()
    assert len(_ch) == 1
    link = _ch[0]
    assert link.tag == 'a'
    player_link = link.attrib['href']
    player_name = _text(link)
    player_maybe_seed = _tail(link)
    return player_link, player_name, player_maybe_seed

def _parse_set_result(set_elem):
    assert set_elem.attrib['class'] == 'result'
    return _text(set_elem)

def _parse_set_score(score_elem):
    assert score_elem.attrib['class'] == 'score'
    return _text(score_elem)

def _parse_home_odds(odds_elem):
    assert odds_elem.attrib['class'] == 'coursew'
    return _text(odds_elem) 

def _parse_away_odds(odds_elem):
    assert odds_elem.attrib['class'] == 'course'
    return _text(odds_elem)

def _parse_bott_row(tr):
    ret = {}
    ch = tr.getchildren()
    match_time = _parse_time(ch[0])
    ret.update({'match_time': match_time})
    player_link, player_name, player_maybe_seed = _parse_player(ch[1])
    ret.update({
        'p1_link': player_link,
        'p1_name': player_name,
        'p1_seed': player_maybe_seed
    })
    ret.update({
        'p1_sets_won': _parse_set_result(ch[2])
    })
    for set_idx, entry in enumerate(ch[3:8]):
        ret.update({'p1_set%d' % (set_idx + 1): _parse_set_score(entry)})
    ret.update({'p1_odds': _parse_home_odds(ch[8])})
    ret.update({'p2_odds': _parse_away_odds(ch[9])})
    return ret

def _parse_nonbott_row(tr, player_idx=2):
    ret = {}
    ch = tr.getchildren()
    player_link, player_name, player_maybe_seed = _parse_player(ch[0])
    ret.update({
        'p2_link': player_link,
        'p2_name': player_name,
        'p2_seed': player_maybe_seed
    })
    ret.update({'p2_sets_won': _parse_set_result(ch[1])})
    for set_idx, entry in enumerate(ch[2:7]):
        ret.update({'p2_set%d' % (set_idx + 1): _parse_set_score(entry)})
    return ret
    
        
def process_table_rows(trs):
    return [_process_table_row(tr) for tr in trs]

In [ ]:
import requests
from lxml import html

class TennisExplorerParser(object):

    numeric_columns = [
        'p1_odds',
        'p2_odds',
        'p1_sets_won',
        'p2_sets_won',
    ] + ['p1_set%d' % set_idx for set_idx in range(1, 6)] + [
        'p2_set%d' % set_idx for set_idx in range(1, 6)
    ]

    def init_parsing(self):
        self.tourney = None
    
    def __init__(self, year, month, day):
        self.url = "https://www.tennisexplorer.com/results/?type=atp-single&year={0}&month={1}&day={2}".format(
            year,
            month,
            day
        )
        self.date = '%s-%s-%s' % (year, month, day)
        self.tree = html.fromstring(requests.get(self.url).content)
        tables = self.tree.xpath(".//table[@class='result']")
        assert len(tables) == 2, "Expected two tables, found %d" % len(tables)
        self.result_table = tables[0]
        _children = self.result_table.getchildren()
        assert len(_children) == 1
        _tbody = _children[0]
        assert _tbody.tag == 'tbody'
        self.table_rows = _tbody.getchildren()
        self.results = []
        
    def _process_table_row(self, tr):
        assert tr.tag == 'tr'
        row_class = tr.attrib['class']
        if row_class == 'head flags':
            self.cur_tourney_info = _parse_head_flags(tr)
        elif 'bott' in row_class:
            self.cur_result = _parse_bott_row(tr)
            self.cur_result.update({
                'date': self.date
            })
            self.cur_result.update(self.cur_tourney_info)
        elif 'one' in row_class or 'two' in row_class:
            self.cur_result.update(_parse_nonbott_row(tr))
            self.results.append(self.cur_result)
            
    def process(self):
        for row in self.table_rows:
            self._process_table_row(row)
            
    def to_df(self):
        res_df = pd.DataFrame(self.results)
        res_df.replace({'': None}, inplace=True)
        for col in numeric_columns:
            res_df[col] = res_df[col].astype(float)
        return res_df

In [ ]:
te = TennisExplorerParser('2010', '05', '06')

In [ ]:
te.process()

In [ ]:
te.to_df()

In [ ]:
res_df.iloc[0]

In [ ]:
from decimal import Decimal

res_df.replace({'': None}, inplace=True)
numeric_columns = [
    'p1_odds',
    'p2_odds',
    'p1_sets_won',
    'p2_sets_won',
] + ['p1_set%d' % set_idx for set_idx in range(1, 6)] + [
    'p2_set%d' % set_idx for set_idx in range(1, 6)
]

for col in numeric_columns:
    res_df[col] = res_df[col].astype(float)

In [ ]:
res_df.head()

In [ ]:
res_df['p2_seed'].iloc[0]

In [ ]:
res_df['tourney_name'].value_counts()

In [ ]:
hf_example = te.tree.find_class('head flags')[-1]

In [ ]:
hf_example = te.table_rows[0]

In [ ]:
q = process_table_rows(te.table_rows)

In [ ]:
q

In [ ]:
row_classes = [x.attrib['class'] for x in te.table_rows]

In [ ]:
html.tostring(te.table_rows[2])

In [ ]:
_parse_nonbott_row(te.table_rows[2])

In [ ]:
q = _parse_bott_row(tr)
q

In [ ]:
regex_strip_string(q['p1_text'])

In [ ]:
children = tr.getchildren()

In [ ]:
html.tostring(children[8])

In [ ]:
children[1].getchildren()[0].tail

In [ ]:
[x.attrib.get('class') for x in tr.getchildren()]

In [ ]:
tr = te.table_rows[1]

In [ ]:
import pandas as pd

pd.Series(row_classes)

In [ ]:
print(html.tostring(hf_example, pretty_print=True))

In [ ]:
_parse_head_flags(hf_example)

In [ ]:
w = hf_example.getchildren()[0]
# zubba = w.getchildren()[1]

In [ ]:
html.tostring(w)

In [ ]:
w.getchildren()[0].getchildren()[-1].tail

In [ ]:
link = w.getchildren()[0]

In [ ]:
html.tostring(link)

In [ ]:
wubba = link.getchildren()[1]

In [ ]:
html.tostring(wubba)

In [ ]:
wubba.tail

In [ ]:
wubba = w.getchildren()[1]
html.tostring(wubba)

In [ ]:
children = hf_example.getchildren()
[x.attrib['class'] for x in children]

In [ ]:
html.tostring(te.result_table.xpath(".//td[@class='t-name']")[3])

In [ ]:
te.table_rows[0].attrib['class']

In [ ]:
q.getchildren()

In [ ]:
import requests
from lxml import html

tree = html.fromstring(requests.get(URL).content)

In [ ]:
tables = tree.xpath(".//table[@class='result']")
result_table = tables[0]

In [ ]:
result_table.getchildren()

In [ ]:
import numpy as np

rows = np.array(tree.xpath(".//tr"))
classes = np.array([x.attrib.get('class', np.nan) for x in rows])

In [ ]:
classes

In [ ]:
none_rows = rows[classes == 'nan']

In [ ]:
html.tostring(none_rows[0])

In [ ]:
html.tostring(rows[0])

In [ ]:
html.tostring(rows[1])

In [ ]:
html.tostring(first_flag)

In [ ]:
link = first_flag.xpath(".//a")[0]

In [ ]:
link.attrib['href']

In [ ]:
flags = tree.find_class('head flags')
html.tostring(flags[-1])

In [ ]:
k